# Generated by Django 2.2 on 2019-04-13 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='imgID',
        ),
    ]
