# Generated by Django 2.2 on 2019-04-15 02:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_remove_image_imgid'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='imgDate',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
