# Generated by Django 2.2 on 2019-04-15 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_image_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='imgUrl',
            new_name='imgName',
        ),
        migrations.RemoveField(
            model_name='image',
            name='imgDate',
        ),
    ]
