# Generated by Django 2.2 on 2019-04-23 04:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20190415_2043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SCMT', models.CharField(max_length=12)),
                ('NS', models.CharField(max_length=8)),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='imgDate',
            field=models.DateField(default=datetime.datetime(2019, 4, 23, 4, 7, 53, 779984, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='image',
            name='imgName',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
