# Generated by Django 2.1.7 on 2019-05-07 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20190423_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='imgDate',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='imgName',
            field=models.CharField(max_length=200),
        ),
    ]
